### ISSUE TITLE
How to attach an old container volume to a new container of this Dockerfile?

### ISSUE THREAD

**Issue by fishfree** [openeuropa/triple-store-dev#114]
I need to add 1111 port to an formerly-running container, so I ran:
```
docker stop triple-store-dev
docker commit triple-store-dev openeuropa/triple-store-dev
docker rm triple-store-dev
docker run --name=triple-store-dev -p 8890:8890 -p 1111:1111 -d openeuropa/triple-store-dev
```
However, when I login in the conductor, I found all my tirple data lost. So I did:
```
sudo su
cd /var/lib/docker/volumes
find ./ -name 'virtuoso' 2> /dev/null
```
There are 2 folders containing virtuoso* files, one is the newly-running containter, so I guess the other one is the removed conatiner, of which the volume fp;der name is 2f0dc5821c26227396bbe6296608a40195811f520b91fc33b0b822617bea2501. So I run:
```
exit
docker stop triple-store-dev
docker run --name=triple-store-dev2 -p 8890:8890 -p 1111:1111 -v /var/lib/docker/volumes/2f0dc5821c26227396bbe6296608a40195811f520b91fc33b0b822617bea2501/_data:/app -d openeuropa/triple-store-dev
```
Again login into the conductor SPARQL page, I sttill cannot find any data in the old container. 

Where is my data? :-(

Any help woud be appreciated VERY VERY much!

**Comment by brummbar** [comment]
Hi @fishfree , sorry for the delay. Unfortunately I am not skilled enough to help with the above, we use this container just for development and only with the vocabularies that are automatically imported, so we never had to keep the storage.

**Comment by fishfree** [comment]
@brummbar I gave up this way. Thank you all the same!
